/**
 * ============================================================
 *  DADOS 100% FICTÍCIOS — APENAS PARA DEMONSTRAÇÃO DO MVP
 * ------------------------------------------------------------
 *  Nenhuma pessoa, empresa, telefone ou valor abaixo é real.
 *  Nomes de empresas foram inventados para o teste do produto.
 *  NÃO usar em produção e NÃO tratar como base de clientes.
 * ============================================================
 *
 * As datas são relativas ao momento em que o seed roda (em dias),
 * para que a demonstração sempre mostre leads realmente parados.
 *
 *   createdDaysAgo      -> há quantos dias o lead entrou
 *   lastContactDaysAgo  -> há quantos dias houve a última interação
 *                          (null = nunca foi contatado)
 *   nextFollowUpDaysAgo -> follow-up agendado (negativo = futuro,
 *                          0 = hoje, positivo = vencido)
 */

export const DEMO_LEADS = [
  {
    name: "Mariana Alves",
    company: "Padaria Sol Nascente (fictícia)",
    phone: "(11) 90000-0001",
    email: "mariana@exemplo.test",
    value: 4500,
    status: "ORCAMENTO",
    source: "WhatsApp",
    createdDaysAgo: 22,
    lastContactDaysAgo: 8,
    nextFollowUpDaysAgo: 1,
    notes: "Pediu orçamento para reforma do balcão de atendimento.",
    history: [
      { daysAgo: 22, type: "CONTACT", message: "Primeiro contato pelo WhatsApp." },
      { daysAgo: 20, type: "NOTE", message: "Levantamento de necessidades feito por telefone." },
      { daysAgo: 8, type: "CONTACT", message: "Orçamento enviado — R$ 4.500." },
    ],
  },
  {
    name: "Ricardo Nunes",
    company: "Óticas Vista Clara (fictícia)",
    phone: "(21) 90000-0002",
    email: "ricardo@exemplo.test",
    value: 2800,
    status: "ORCAMENTO",
    source: "Indicação",
    createdDaysAgo: 14,
    lastContactDaysAgo: 5,
    nextFollowUpDaysAgo: 0,
    notes: "Indicado por cliente antigo.",
    history: [
      { daysAgo: 14, type: "CONTACT", message: "Contato inicial por indicação." },
      { daysAgo: 5, type: "CONTACT", message: "Orçamento enviado — R$ 2.800." },
    ],
  },
  {
    name: "Camila Ferreira",
    company: "TransLog Cargas (fictícia)",
    phone: "(41) 90000-0003",
    email: "camila@exemplo.test",
    value: 7200,
    status: "NEGOCIACAO",
    source: "Site",
    createdDaysAgo: 40,
    lastContactDaysAgo: 12,
    nextFollowUpDaysAgo: 5,
    notes: "Comparando com dois concorrentes. Sensível a prazo de entrega.",
    history: [
      { daysAgo: 40, type: "CONTACT", message: "Formulário do site preenchido." },
      { daysAgo: 33, type: "CONTACT", message: "Reunião de apresentação realizada." },
      { daysAgo: 25, type: "CONTACT", message: "Proposta enviada — R$ 7.200." },
      { daysAgo: 18, type: "RESPONSE", message: "Cliente pediu desconto de 10%." },
      { daysAgo: 12, type: "FOLLOW_UP", message: "Enviada contraproposta com 5% de desconto." },
    ],
  },
  {
    name: "Bruno Tavares",
    company: "Studio Pilates Movimento (fictício)",
    phone: "(31) 90000-0004",
    email: "bruno@exemplo.test",
    value: 1800,
    status: "NOVO",
    source: "Instagram",
    createdDaysAgo: 9,
    lastContactDaysAgo: null,
    nextFollowUpDaysAgo: null,
    notes: "Chegou pelo anúncio do Instagram e nunca recebeu retorno.",
    history: [
      { daysAgo: 9, type: "NOTE", message: "Lead capturado pelo anúncio do Instagram." },
    ],
  },
  {
    name: "Patrícia Gomes",
    company: "Clínica OdontoVida (fictícia)",
    phone: "(11) 90000-0005",
    email: "patricia@exemplo.test",
    value: 15400,
    status: "NEGOCIACAO",
    source: "Indicação",
    createdDaysAgo: 55,
    lastContactDaysAgo: 15,
    nextFollowUpDaysAgo: 8,
    notes: "Maior oportunidade em aberto. Decisão depende do sócio.",
    history: [
      { daysAgo: 55, type: "CONTACT", message: "Reunião inicial na clínica." },
      { daysAgo: 44, type: "CONTACT", message: "Proposta enviada — R$ 15.400." },
      { daysAgo: 30, type: "RESPONSE", message: "Cliente pediu para aguardar aprovação do sócio." },
      { daysAgo: 15, type: "FOLLOW_UP", message: "Follow-up enviado perguntando sobre a aprovação." },
    ],
  },
  {
    name: "Eduardo Lima",
    company: "Mercado Bom Preço (fictício)",
    phone: "(19) 90000-0006",
    email: "eduardo@exemplo.test",
    value: 3200,
    status: "CONTATO",
    source: "Telefone",
    createdDaysAgo: 11,
    lastContactDaysAgo: 4,
    nextFollowUpDaysAgo: 1,
    notes: "Quer entender melhor o escopo antes de pedir orçamento.",
    history: [
      { daysAgo: 11, type: "CONTACT", message: "Ligação recebida pedindo informações." },
      { daysAgo: 4, type: "CONTACT", message: "Explicado o escopo por telefone." },
    ],
  },
  {
    name: "Fernanda Rocha",
    company: "Academia Corpo Ativo (fictícia)",
    phone: "(51) 90000-0007",
    email: "fernanda@exemplo.test",
    value: 9800,
    status: "ORCAMENTO",
    source: "Site",
    createdDaysAgo: 60,
    lastContactDaysAgo: 21,
    nextFollowUpDaysAgo: 14,
    notes: "Orçamento parado há três semanas. Vale uma tentativa de resgate.",
    history: [
      { daysAgo: 60, type: "CONTACT", message: "Contato pelo site." },
      { daysAgo: 50, type: "CONTACT", message: "Visita técnica realizada." },
      { daysAgo: 21, type: "CONTACT", message: "Orçamento enviado — R$ 9.800." },
    ],
  },
  {
    name: "Thiago Barbosa",
    company: "Auto Center Veloz (fictício)",
    phone: "(11) 90000-0008",
    email: "thiago@exemplo.test",
    value: 5600,
    status: "ORCAMENTO",
    source: "WhatsApp",
    createdDaysAgo: 18,
    lastContactDaysAgo: 7,
    nextFollowUpDaysAgo: 0,
    notes: "Demonstrou urgência no primeiro contato e depois sumiu.",
    history: [
      { daysAgo: 18, type: "CONTACT", message: "Contato pelo WhatsApp." },
      { daysAgo: 12, type: "RESPONSE", message: "Cliente perguntou prazo de execução." },
      { daysAgo: 7, type: "CONTACT", message: "Orçamento enviado — R$ 5.600." },
    ],
  },
  {
    name: "Juliana Castro",
    company: "Pet Shop Amigo Fiel (fictício)",
    phone: "(11) 90000-0009",
    email: "juliana@exemplo.test",
    value: 2400,
    status: "NOVO",
    source: "Indicação",
    createdDaysAgo: 2,
    lastContactDaysAgo: null,
    nextFollowUpDaysAgo: null,
    notes: "Lead recente, ainda dentro do prazo.",
    history: [{ daysAgo: 2, type: "NOTE", message: "Lead cadastrado por indicação." }],
  },
  {
    name: "Marcelo Dias",
    company: "Construtora Horizonte (fictícia)",
    phone: "(11) 90000-0010",
    email: "marcelo@exemplo.test",
    value: 24000,
    status: "NEGOCIACAO",
    source: "Evento",
    createdDaysAgo: 35,
    lastContactDaysAgo: 6,
    nextFollowUpDaysAgo: -1,
    notes: "Maior ticket da base. Negociando escopo por etapas.",
    history: [
      { daysAgo: 35, type: "CONTACT", message: "Contato feito em feira do setor." },
      { daysAgo: 28, type: "CONTACT", message: "Proposta inicial enviada — R$ 24.000." },
      { daysAgo: 15, type: "RESPONSE", message: "Cliente pediu divisão do projeto em duas etapas." },
      { daysAgo: 6, type: "FOLLOW_UP", message: "Enviada proposta revisada em duas etapas." },
    ],
  },
  {
    name: "Aline Moreira",
    company: "Restaurante Sabor da Terra (fictício)",
    phone: "(11) 90000-0011",
    email: "aline@exemplo.test",
    value: 3900,
    status: "CONTATO",
    source: "WhatsApp",
    createdDaysAgo: 6,
    lastContactDaysAgo: 1,
    nextFollowUpDaysAgo: -2,
    notes: "Conversa acontecendo agora, nada parado.",
    history: [
      { daysAgo: 6, type: "CONTACT", message: "Primeiro contato pelo WhatsApp." },
      { daysAgo: 1, type: "CONTACT", message: "Alinhamento de escopo por telefone." },
    ],
  },
  {
    name: "Rafael Pinto",
    company: "Escola Futuro Brilhante (fictícia)",
    phone: "(62) 90000-0012",
    email: "rafael@exemplo.test",
    value: 11500,
    status: "ORCAMENTO",
    source: "Site",
    createdDaysAgo: 27,
    lastContactDaysAgo: 9,
    nextFollowUpDaysAgo: 2,
    notes: "Orçamento aprovado internamente, aguardando assinatura.",
    history: [
      { daysAgo: 27, type: "CONTACT", message: "Contato pelo site." },
      { daysAgo: 20, type: "CONTACT", message: "Reunião com a diretoria." },
      { daysAgo: 9, type: "CONTACT", message: "Orçamento enviado — R$ 11.500." },
    ],
  },
  {
    name: "Vanessa Duarte",
    company: "Salão Beleza Real (fictício)",
    phone: "(11) 90000-0013",
    email: "vanessa@exemplo.test",
    value: 1600,
    status: "PERDIDO",
    source: "Instagram",
    createdDaysAgo: 48,
    lastContactDaysAgo: 30,
    nextFollowUpDaysAgo: null,
    notes: "Fechou com concorrente por preço.",
    history: [
      { daysAgo: 48, type: "CONTACT", message: "Contato pelo Instagram." },
      { daysAgo: 40, type: "CONTACT", message: "Orçamento enviado — R$ 1.600." },
      { daysAgo: 30, type: "STATUS_CHANGE", message: "Status alterado para Perdido — fechou com concorrente." },
    ],
  },
  {
    name: "Gustavo Mendes",
    company: "Distribuidora Norte Sul (fictícia)",
    phone: "(85) 90000-0014",
    email: "gustavo@exemplo.test",
    value: 8700,
    status: "GANHO",
    source: "Indicação",
    createdDaysAgo: 52,
    lastContactDaysAgo: 10,
    nextFollowUpDaysAgo: null,
    notes: "Fechou depois de um follow-up de resgate — exemplo de oportunidade recuperada.",
    history: [
      { daysAgo: 52, type: "CONTACT", message: "Contato inicial por indicação." },
      { daysAgo: 45, type: "CONTACT", message: "Orçamento enviado — R$ 8.700." },
      { daysAgo: 30, type: "NOTE", message: "Sem resposta do cliente por duas semanas." },
      { daysAgo: 16, type: "FOLLOW_UP", message: "Follow-up de resgate enviado pelo FOLLOW." },
      { daysAgo: 13, type: "RESPONSE", message: "Cliente retomou a conversa e pediu a nota." },
      { daysAgo: 10, type: "STATUS_CHANGE", message: "Status alterado para Ganho." },
    ],
  },
  {
    name: "Larissa Campos",
    company: "Café Grão Fino (fictício)",
    phone: "(11) 90000-0015",
    email: "larissa@exemplo.test",
    value: 2100,
    status: "GANHO",
    source: "Site",
    createdDaysAgo: 33,
    lastContactDaysAgo: 18,
    nextFollowUpDaysAgo: null,
    notes: "Ciclo curto, fechou sem precisar de follow-up.",
    history: [
      { daysAgo: 33, type: "CONTACT", message: "Contato pelo site." },
      { daysAgo: 25, type: "CONTACT", message: "Orçamento enviado — R$ 2.100." },
      { daysAgo: 18, type: "STATUS_CHANGE", message: "Status alterado para Ganho." },
    ],
  },
  {
    name: "Diego Ramos",
    company: "Lavanderia Água Viva (fictícia)",
    phone: "(11) 90000-0016",
    email: "diego@exemplo.test",
    value: 3400,
    status: "PERDIDO",
    source: "Telefone",
    createdDaysAgo: 70,
    lastContactDaysAgo: 45,
    nextFollowUpDaysAgo: null,
    notes: "Adiou o projeto por tempo indeterminado.",
    history: [
      { daysAgo: 70, type: "CONTACT", message: "Ligação recebida." },
      { daysAgo: 62, type: "CONTACT", message: "Orçamento enviado — R$ 3.400." },
      { daysAgo: 45, type: "STATUS_CHANGE", message: "Status alterado para Perdido — projeto adiado." },
    ],
  },
  {
    name: "Sofia Nogueira",
    company: "Imobiliária Terra Firme (fictícia)",
    phone: "(48) 90000-0017",
    email: "sofia@exemplo.test",
    value: 6300,
    status: "ORCAMENTO",
    source: "Site",
    createdDaysAgo: 12,
    lastContactDaysAgo: 3,
    nextFollowUpDaysAgo: 0,
    notes: "Acabou de entrar na faixa de atenção.",
    history: [
      { daysAgo: 12, type: "CONTACT", message: "Contato pelo site." },
      { daysAgo: 3, type: "CONTACT", message: "Orçamento enviado — R$ 6.300." },
    ],
  },
  {
    name: "Henrique Vasconcelos",
    company: "Metalúrgica Aço Forte (fictícia)",
    phone: "(11) 90000-0018",
    email: "henrique@exemplo.test",
    value: 18900,
    status: "NEGOCIACAO",
    source: "Evento",
    createdDaysAgo: 44,
    lastContactDaysAgo: 11,
    nextFollowUpDaysAgo: 4,
    notes: "Negociação avançada travada na condição de pagamento.",
    history: [
      { daysAgo: 44, type: "CONTACT", message: "Contato feito em evento do setor." },
      { daysAgo: 36, type: "CONTACT", message: "Proposta enviada — R$ 18.900." },
      { daysAgo: 22, type: "RESPONSE", message: "Cliente pediu parcelamento em 6x." },
      { daysAgo: 11, type: "FOLLOW_UP", message: "Enviada condição de pagamento revisada." },
    ],
  },
];
